In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df =pd.read_csv('/content/drive/MyDrive/Deep Learning/Lecture 11-20/Admission_Predict_Ver1.1.csv')
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
495,496,332,108,5,4.5,4.0,9.02,1,0.87
496,497,337,117,5,5.0,5.0,9.87,1,0.96
497,498,330,120,5,4.5,5.0,9.56,1,0.93
498,499,312,103,4,4.0,5.0,8.43,0,0.73
499,500,327,113,4,4.5,4.5,9.04,0,0.84

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         500 non-null    int64
 1   GRE Score          500 non-null    int64
 2   TOEFL Score        500 non-null    int64
 3   University Rating  500 non-null    int64
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [5]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [8]:
df.drop(['Serial No.'],axis=1,inplace=True)

KeyError: "['Serial No.'] not found in axis"

In [9]:
df

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...
495,332,108,5,4.5,4.0,9.02,1,0.87
496,337,117,5,5.0,5.0,9.87,1,0.96
497,330,120,5,4.5,5.0,9.56,1,0.93
498,312,103,4,4.0,5.0,8.43,0,0.73
499,327,113,4,4.5,4.5,9.04,0,0.84

In [11]:
# jabb hame lower bound and upper bound pata rehta hai to ham us time pe min max scaling karte hai
X=df.drop(['Chance of Admit '],axis=1)
y=df['Chance of Admit ']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [15]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()

In [28]:
X_train_scaled=ms.fit_transform(X_train)
X_test_scaled=ms.fit_transform(X_test)

In [17]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model=Sequential()

model.add(Dense(7,activation='relu',input_dim=7))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(loss='mean_squared_error',optimizer='Adam')

In [26]:
model.fit(X_train_scaled,y_train,epochs=10,validation_split=0.2)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.4911 - val_loss: 0.5410
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.4589 - val_loss: 0.5078
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4284 - val_loss: 0.4777
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.4002 - val_loss: 0.4509
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3743 - val_loss: 0.4257
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3508 - val_loss: 0.4021
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3286 - val_loss: 0.3808
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.3085 - val_loss: 0.3607
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.2894 - val_loss: 0.3411
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.2711 - val_loss: 0.3223

In [29]:
y_pred=model.predict(X_test_scaled)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

ValueError: continuous is not supported

In [31]:
y_test

361    0.93
73     0.84
374    0.39
155    0.77
104    0.74
       ...
110    0.61
318    0.79
428    0.69
29     0.54
437    0.61
Name: Chance of Admit , Length: 165, dtype: float64

In [32]:
y_pred

array([[0.39360866],
       [0.26449066],
       [0.13904132],
       [0.1338774 ],
       [0.40402356],
       [0.36125588],
       [0.11375087],
       [0.08421201],
       [0.3390703 ],
       [0.28900054],
       [0.1662912 ],
       [0.15633062],
       [0.30736646],
       [0.35046408],
       [0.39696923],
       [0.07072598],
       [0.31221196],
       [0.23094876],
       [0.08287496],
       [0.15239556],
       [0.28564745],
       [0.07306672],
       [0.26274818],
       [0.38191023],
       [0.39464512],
       [0.23929296],
       [0.3182014 ],
       [0.36196843],
       [0.15974541],
       [0.2500798 ],
       [0.07149784],
       [0.15972677],
       [0.12296936],
       [0.32761684],
       [0.30461764],
       [0.34258878],
       [0.16526072],
       [0.33070675],
       [0.20976134],
       [0.39037654],
       [0.41364533],
       [0.23867597],
       [0.29747626],
       [0.34450358],
       [0.35354212],
       [0.12355568],
       [0.40499604],
       [0.3329319 ],
       [0.30899206],
       [0.3087364 ],
       [0.2545894 ],
       [0.10992093],
       [0.10245398],
       [0.16076165],
       [0.33049327],
       [0.05212454],
       [0.4180945 ],
       [0.17439213],
       [0.12325439],
       [0.22775432],
       [0.21728772],
       [0.28340444],
       [0.127115  ],
       [0.00095976],
       [0.09939086],
       [0.16039772],
       [0.33962092],
       [0.2868409 ],
       [0.08715992],
       [0.12466523],
       [0.25392956],
       [0.3877349 ],
       [0.19378178],
       [0.12557174],
       [0.15056908],
       [0.17789248],
       [0.16193058],
       [0.36042818],
       [0.09533451],
       [0.08117257],
       [0.17900518],
       [0.2525613 ],
       [0.04969578],
       [0.29648662],
       [0.34000653],
       [0.37886637],
       [0.09168883],
       [0.29783422],
       [0.23314205],
       [0.16849488],
       [0.32228315],
       [0.35678464],
       [0.32971305],
       [0.11416775],
       [0.42588264],
       [0.09146726],
       [0.14815213],
       [0.42320633],
       [0.4556937 ],
       [0.12091327],
       [0.36142677],
       [0.10983948],
       [0.09403705],
       [0.17710692],
       [0.30342582],
       [0.03953541],
       [0.21409814],
       [0.33304557],
       [0.37276447],
       [0.07181419],
       [0.32249188],
       [0.3259475 ],
       [0.3261579 ],
       [0.358659  ],
       [0.06974132],
       [0.34311748],
       [0.17039698],
       [0.29225177],
       [0.05851291],
       [0.387242  ],
       [0.14147231],
       [0.36410335],
       [0.3314737 ],
       [0.16036588],
       [0.36560497],
       [0.20641771],
       [0.02477611],
       [0.33430332],
       [0.40549895],
       [0.0821757 ],
       [0.35791498],
       [0.23841976],
       [0.2531042 ],
       [0.0734861 ],
       [0.47674754],
       [0.06123633],
       [0.27775884],
       [0.3556636 ],
       [0.35818526],
       [0.11057916],
       [0.20174009],
       [0.15296051],
       [0.33945164],
       [0.05469061],
       [0.3934851 ],
       [0.16543171],
       [0.3429937 ],
       [0.13800006],
       [0.10457914],
       [0.12234509],
       [0.33547956],
       [0.11196381],
       [0.27895087],
       [0.15961249],
       [0.06152573],
       [0.27585915],
       [0.38800552],
       [0.3223598 ],
       [0.06046983],
       [0.14682342],
       [0.06843987],
       [0.3934478 ],
       [0.18514182],
       [0.07067959],
       [0.40581897]], dtype=float32)